### ISSUE TITLE
AgentExtension-XX  Pipedrive doesn't have phone number field for users.

### ISSUE THREAD

**Issue by mattpr** [modestcrab/3CX-Pipedrive-Integration#1]
Readme says:

> Go to Pipedrive and create a contract for each of your user that will use the system. Make sure their email on pipedrive matches the email on 3CX. In the phone number field enter AgentExtension-XX where XX represents the users extension in 3cx.

...but pipedrive apparently doesn't have phone number field on a user level.

https://devcommunity.pipedrive.com/t/how-to-add-update-phone-number-to-a-user/3638

What am I missing?

**Comment by modestcrab** [comment]
> Readme says:
> 
> > Go to Pipedrive and create a contract for each of your user that will use the system. Make sure their email on pipedrive matches the email on 3CX. In the phone number field enter AgentExtension-XX where XX represents the users extension in 3cx.
> 
> ...but pipedrive apparently doesn't have phone number field on a user level.
> 
> https://devcommunity.pipedrive.com/t/how-to-add-update-phone-number-to-a-user/3638
> 
> What am I missing?

You need to create a new contact in the address book.
Go to contacts > people > +person

Add a new person that is your employee and then add a phone number.

Sorry if this wasn't clear...

**Comment by mattpr** [comment]
Ah, "contract" is supposed to be "contact".  Got it.
